-- Seed consultation_log from Excel DIARIO DE PACIENTES 2026
DO $$
DECLARE
  synapsia_id uuid;
  admin_user_id uuid;
  r record;
BEGIN
  SELECT id INTO synapsia_id FROM public.health_units WHERE name = 'Synapsia Consultorio';
  IF synapsia_id IS NULL THEN
    INSERT INTO public.health_units (name, description) VALUES ('Synapsia Consultorio', 'Consultorios m�dicos para atenci�n de especialistas') RETURNING id INTO synapsia_id;
  END IF;
  -- Use the first admin user as created_by, or a dummy UUID
  SELECT id INTO admin_user_id FROM auth.users LIMIT 1;
  IF admin_user_id IS NULL THEN
    admin_user_id := '00000000-0000-0000-0000-000000000000'::uuid;
  END IF;

  -- Helper function to parse dd-mmm dates in 2026
  WITH data AS (
    SELECT * FROM (VALUES
      ('01-jun','Selene Garcia','Thomas Pichardo','Psiquiatria',1100,'Efectivo',1100,'01-jun','',False,'','',''),
      ('01-jun','Selene Garcia','Fernando Perez Santana','Psiquiatria',1400,'Tarjera',1400,'01-jun','Synapsia',False,'','',''),
      ('01-jun','Rodrigo Márquez','Emmanuel Terrón Enriquez','Psicologia',1100,'Efectivo',1100,'01-jun','',False,'','',''),
      ('01-jun','Selene Garcia','Lorena Valdez','Psiquiatria',1100,'Transferencia',1100,'01-jun','Médico',False,'','','envio compr.'),
      ('01-jun','Selene Garcia','Fabian Martínez González','Psiquiatria',1100,'Efectivo',1100,'01-jun','',False,'','',''),
      ('01-jun','Rodrigo Márquez','Tonantzin Tello','Psicologia',1100,'Efectivo',1100,'01-jun','',False,'','',''),
      ('01-jun','Selene Garcia','Giuliana castro','Psiquiatria',1100,'Efectivo',1100,'01-jun','',False,'','',''),
      ('01-jun','Rodrigo Márquez','Rodrigo Feliz','Psicologia',0,'',NULL,'','',False,'','',''),
      ('01-jun','Diana Gómez','Miguel Angel Davila','Psiquiatria',1100,'Efectivo',1100,'01-jun','',False,'','',''),
      ('01-jun','Diana Gómez','Lucio Gonzalez','Psiquiatria',1100,'Efectivo',1100,'01-jun','',False,'','',''),
      ('01-jun','David Medina','Miguel Angel Davila','Psicologia',800,'Efectivo',800,'01-jun','',False,'','',''),
      ('01-jun','Octavio Márquez','Sigfrid Leonardo','Psiquiatria',500,'',500,'01-jun','',False,'','',''),
      ('01-jun','Diana Gómez','Dayana Yamileth Calzada','Psiquiatria',1400,'Efectivo',1400,'01-jun','',False,'','',''),
      ('01-jun','Rodrigo Márquez','Fernando Guillen','Psicologia',1100,'Tarjera',1100,'01-jun','Dr. Márquez',False,'','',''),
      ('01-jun','Rodrigo Márquez','Pepe y mamá','Psicologia',0,'',NULL,'','',False,'','',''),
      ('02-jun','Selene Garcia','Carlos Uriel Acevedo','Psiquiatria',1100,'Efectivo',1100,'02-jun','',False,'','',''),
      ('02-jun','Selene Garcia','Paz González','Psiquiatria',1100,'Transferencia',1100,'07-jun','Médico',False,'','','envio compr.'),
      ('02-jun','Selene Garcia','Christian Nava','Psiquiatria',1100,'Efectivo',1100,'02-jun','',False,'','',''),
      ('02-jun','Selene Garcia','Mary Frasco','Psiquiatria',1100,'Efectivo',1100,'02-jun','',False,'','',''),
      ('02-jun','Selene Garcia','Naim Mancilla','Psiquiatria',1100,'Efectivo',1100,'02-jun','',False,'','',''),
      ('02-jun','Selene Garcia','Stephanie Matta Bobadilla','Psiquiatria',1400,'Transferencia',1400,'29-may','Médico',False,'','','envio compr.'),
      ('02-jun','Selene Garcia','Guadalupe Neria Rico','Psiquiatria',1100,'Transferencia',1100,'02-jun','',False,'','','envio compr.'),
      ('02-jun','Selene Garcia','Andrea Baron Dominguez','Psiquiatria',1100,'Efectivo',1100,'02-jun','',False,'','',''),
      ('02-jun','Rodrigo Márquez','Geovana','Psicologia',0,'',NULL,'','',False,'','',''),
      ('02-jun','Wendoline Flores','???','Pediatria',250,'Efectivo',250,'02-jun','',False,'','',''),
      ('02-jun','Diana Gómez','Cesar Vilchis Peñaloza','Psiquiatria',1400,'Tarjera',1400,'02-jun','Synapsia',False,'','',''),
      ('02-jun','Selene Garcia','Yatsiri Pineda','Psiquiatria',1100,'Transferencia',1100,'04-jun','Médico',False,'','','envio compr.'),
      ('02-jun','Diana Gómez','Evelyn Flores','Psiquiatria',1400,'Transferencia',1400,'02-jun','Synapsia',True,'faltan datos','','envio compr.'),
      ('02-jun','Selene Garcia','Jose Juan Vázquez','Psiquiatria',500,'',500,'02-jun','',False,'','',''),
      ('02-jun','Diana Gómez','Tannia Samara Perez','Psiquiatria',1100,'Tarjera',1100,'02-jun','Synapsia',False,'','',''),
      ('02-jun','Selene Garcia','Ángel Alberto Esquivel','Psiquiatria',1100,'Transferencia',1100,'04-jun','Synapsia',True,'08-jun','2216','envio compr.'),
      ('02-jun','Selene Garcia','Natalia Vázquez','Psiquiatria',500,'',500,'02-jun','',False,'','',''),
      ('03-jun','Selene Garcia','Ángel Josué Sánchez','Psiquiatria',1100,'Efectivo',1100,'03-jun','',False,'','',''),
      ('03-jun','David Medina','Paola','Psicologia',800,'',800,'03-jun','',False,'','',''),
      ('03-jun','Selene Garcia','Maria Sampedro','Psiquiatria',1400,'Transferencia',1400,'03-jun','Médico',False,'','','envio compr.'),
      ('03-jun','David Medina','Enrique','Psicologia',300,'',300,'03-jun','',False,'','',''),
      ('03-jun','Jessica Vazquez','Christin Cienfuego','Psicologia',900,'Efectivo',900,'03-jun','',False,'','',''),
      ('03-jun','Rodrigo Márquez','Margarita Morales','Psicologia',1100,'Efectivo',1100,'03-jun','',False,'','',''),
      ('03-jun','Selene Garcia','Diego Flores Glz','Psiquiatria',700,'',700,'03-jun','',False,'','',''),
      ('03-jun','Rodrigo Márquez','Francisco Cervantes','Psicologia',1100,'Tarjera',1100,'03-jun','Synapsia',True,'08-jun','2211',''),
      ('03-jun','Rodrigo Márquez','Guadalupe Solano','Psicologia',0,'',NULL,'','',False,'','',''),
      ('03-jun','Jessica Vazquez','Isabella Antillon','Psicologia',900,'Transferencia',900,'03-jun','Médico',False,'','','envio compr.'),
      ('03-jun','Rodrigo Márquez','Gabriela Villicaña','Psicologia',1100,'Efectivo',1100,'03-jun','',False,'','',''),
      ('03-jun','David Medina','Amir Soto','Psicologia',800,'',800,'03-jun','',False,'','',''),
      ('03-jun','Diana Gómez','Sara Sabina Robles','Psiquiatria',1100,'Tarjera',1100,'03-jun','Synapsia',True,'08-jun','2212',''),
      ('03-jun','Jessica Vazquez','Aisha','Psicologia',1044,'Tarjera',1044,'03-jun','Jessi',False,'','',''),
      ('03-jun','Octavio Márquez','Luis Brunett','Psiquiatria',1160,'Tarjera',1160,'03-jun','Synapsia',True,'08-jun','2213',''),
      ('03-jun','Diana Gómez','Irving Avila','Psiquiatria',1100,'Tarjera',1100,'03-jun','Synapsia',True,'08-jun','2214',''),
      ('03-jun','David Medina','Dulce Gomez','Psicologia',800,'Efectivo',800,'03-jun','',False,'','',''),
      ('03-jun','Jessica Vazquez','Norma Wendoline','Psicologia',900,'Transferencia',900,'03-jun','Médico',False,'','','envio compr.'),
      ('03-jun','Diana Gómez','Ricardo Santiago Contreras','Psiquiatria',1100,'Tarjera',1100,'03-jun','Synapsia',False,'','',''),
      ('03-jun','David Medina','Alejandro Santin','Psicologia',800,'Transferencia',800,'03-jun','Médico',False,'','','envio compr.'),
      ('03-jun','Diana Gómez','Lydia Garcia','Psicologia',1100,'Tarjera',1100,'03-jun','Synapsia',True,'08-jun','2215',''),
      ('04-jun','David Medina','Antonio Dorantes','Psicologia',800,'',800,'04-jun','',False,'','',''),
      ('04-jun','Selene Garcia','Carlos Abraham Martínez','Psiquiatria',1400,'Tarjera',1400,'04-jun','Synapsia',False,'','',''),
      ('04-jun','Selene Garcia','Marilyn Abundis','Psiquiatria',1100,'Transferencia',1100,'06-jun','Médico',False,'','','envio compr.'),
      ('04-jun','Selene Garcia','Matías Gabriel Rivera','Psiquiatria',1100,'Efectivo',1100,'04-jun','',False,'','',''),
      ('04-jun','Selene Garcia','Carlo Cravioto','Psiquiatria',900,'Transferencia',900,'04-jun','Médico',False,'','','envio compr.'),
      ('04-jun','Selene Garcia','David Osorio Flores','Psiquiatria',1100,'Tarjera',1100,'04-jun','Synapsia',False,'','',''),
      ('04-jun','Selene Garcia','David Iniestra Becerra','Psiquiatria',1100,'',NULL,'','',False,'','',''),
      ('04-jun','Itzel','Aaron Garcia','Psicologia',0,'',NULL,'','',False,'','',''),
      ('04-jun','Diana Gómez','Aaron Garcia','Psiquiatria',1400,'Tarjera',1400,'04-jun','Synapsia',False,'','',''),
      ('04-jun','Selene Garcia','Atala Mayer','Psiquiatria',580,'Transferencia',580,'04-jun','Synapsia',True,'08-jun','2217',''),
      ('04-jun','Jessica Vazquez','Daniela Rivera','Psicologia',1400,'Efectivo',1400,'04-jun','',False,'','',''),
      ('04-jun','Diana Gómez','Ana Karen Wells','Psiquiatria',1100,'Tarjera',1100,'04-jun','Synapsia',True,'08-jun','2218',''),
      ('04-jun','Jessica Vazquez','Diego Emilio','Psicologia',900,'Efectivo',900,'04-jun','',False,'','',''),
      ('04-jun','Diana Gómez','Sandra Evelyn Mejia','Psiquiatria',1100,'Tarjera',1100,'04-jun','Synapsia',True,'08-jun','2219',''),
      ('04-jun','Diana Gómez','Lorena Urteaga','Psiquiatria',1100,'Transferencia',1100,'04-jun','Médico',False,'','','envio compr.'),
      ('05-jun','Selene Garcia','Carlos Manuel Velasco','Psiquiatria',1400,'Efectivo',1400,'05-jun','',False,'','',''),
      ('05-jun','Selene Garcia','José Francisco Martínez','Psiquiatria',500,'',500,'05-jun','',False,'','',''),
      ('05-jun','Rodrigo Márquez','Ofelia Escamilla','Psicologia',0,'',NULL,'','',False,'','',''),
      ('05-jun','Jessica Vazquez','Axel Diaz','Evaluación Global',2000,'Efectivo',2000,'05-jun','',False,'','',''),
      ('05-jun','Alejandra Tonanzin','???','Psicologia',0,'',NULL,'','',False,'','',''),
      ('05-jun','Alejandra Tonanzin','???','Psicologia',0,'',NULL,'','',False,'','',''),
      ('05-jun','Jessica Vazquez','Christian Cienfuego','Psicologia',900,'Efectivo',900,'05-jun','',False,'','',''),
      ('05-jun','Itzel','Aaron Garcia','Evaluación Global',6850,'Efectivo',6850,'05-jun','',False,'','',''),
      ('05-jun','Jessica Vazquez','Lucia Berra','Psicologia',800,'Efectivo',800,'05-jun','',False,'','',''),
      ('05-jun','Jessica Vazquez','Axel Suarez','Psicologia',900,'Efectivo',900,'05-jun','',False,'','',''),
      ('05-jun','Jessica Vazquez','Eduardo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('05-jun','Octavio Márquez','Alejandro Odabachea','Psiquiatria',1160,'Transferencia',1160,'07-jun','Synapsia',True,'08-jun','2224','envio compr.'),
      ('06-jun','Selene Garcia','Fernanda Zoé Ferrer','Psiquiatria',1100,'Tarjera',1100,'06-jun','Synapsia',True,'08-jun','2220',''),
      ('06-jun','Selene Garcia','Emiliano Estrada Cruz','Psiquiatria',1100,'Tarjera',1100,'06-jun','Synapsia',True,'11-jun','2227',''),
      ('06-jun','Diana Gómez','Ana Maria Ceballos','Psiquiatria',1100,'Efectivo',1100,'06-jun','',False,'','',''),
      ('06-jun','Selene Garcia','Josué Emiliano García','Psiquiatria',1100,'Efectivo',1100,'06-jun','',False,'','','debe $100'),
      ('06-jun','Diana Gómez','Martin Ruiz','Psiquiatria',1400,'Tarjera',1400,'06-jun','Synapsia',True,'faltan datos','',''),
      ('06-jun','Diana Gómez','Jazmin Pacheco','Psiquiatria',1400,'Tarjera',1400,'06-jun','Synapsia',False,'','',''),
      ('06-jun','Diana Gómez','Fabiola del Rayo','Psiquiatria',1100,'Tarjera',1100,'06-jun','Synapsia',True,'08-jun','2222',''),
      ('06-jun','Rodrigo Márquez','Jose Manuel Ruiz','Psicologia',1100,'Tarjera',1100,'06-jun','Synapsia',True,'08-jun','2221',''),
      ('06-jun','Rodrigo Márquez','Pablo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('06-jun','Diana Gómez','Renata Mourra','Psiquiatria',1400,'Tarjera',1400,'06-jun','Synapsia',False,'','',''),
      ('06-jun','Diana Gómez','Antonio Morales','Psiquiatria',1100,'Tarjera',1100,'06-jun','Synapsia',True,'08-jun','2223',''),
      ('06-jun','Diana Gómez','Diana Sánchez','Psiquiatria',1400,'Efectivo',1100,'06-jun','',False,'','',''),
      ('08-jun','Selene Garcia','Marjorie Joanna Mejia','Psiquiatria',1400,'Efectivo',1400,'08-jun','',False,'','',''),
      ('08-jun','Selene Garcia','Bruno Valdez Hernandez','Psiquiatria',1100,'Transferencia',1100,'08-jun','Synapsia',True,'08-jun','2225','envio compr.'),
      ('08-jun','Selene Garcia','Marisol Sánchez Aguirre','Psiquiatria',1100,'Tarjera',1100,'08-jun','Synapsia',True,'11-jun','2228',''),
      ('08-jun','Selene Garcia','Andrea Astrid De Leó','Psiquiatria',1100,'Transferencia',1100,'08-jun','Synapsia',True,'11-jun','2229','envio compr.'),
      ('08-jun','Jessica Vazquez','Christian Cienfuego','Psicologia',900,'',NULL,'','',False,'','',''),
      ('08-jun','Jessica Vazquez','Sofia Bonales','Psicologia',900,'Transferencia',900,'16-jun','Médico',False,'','','envio comp.'),
      ('08-jun','Itzel','Aaron Garcia','Evaluación Global',0,'',NULL,'','',False,'','',''),
      ('08-jun','Rodrigo Márquez','Aaron Garcia','Psicologia',1100,'Tarjera',1100,'08-jun','Dr. Márquez',False,'','',''),
      ('08-jun','Jessica Vazquez','Paulo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('08-jun','Octavio Márquez','Sigfrid Leonardo','Psiquiatria',500,'',500,'08-jun','',False,'','',''),
      ('08-jun','Diana Gómez','Pedro Nuñez','Psiquiatria',1100,'Efectivo',1100,'08-jun','',False,'','',''),
      ('08-jun','Rodrigo Márquez','Carolla','Psicologia',1100,'Transferencia',1100,'08-jun','Médico',False,'','','envio compr.'),
      ('08-jun','Jessica Vazquez','Rene Santin','Psicologia',928,'Transferencia',928,'09-jun','Médico',False,'','','envio compr.'),
      ('08-jun','Diana Gómez','Juan Antonio Dorante','Psiquiatria',1100,'Tarjera',1100,'08-jun','Synapsia',False,'','',''),
      ('08-jun','Rodrigo Márquez','Obed Gonzalez','Psicologia',1100,'Tarjera',1100,'08-jun','Synapsia',True,'11-jun','2230',''),
      ('08-jun','Octavio Márquez','Laura Angelica Rodea Santana','Psiquiatria',0,'',NULL,'','',False,'','',''),
      ('08-jun','Jessica Vazquez','Sofia Alanis','Psicologia',900,'Efectivo',900,'08-jun','',False,'','',''),
      ('08-jun','Diana Gómez','Lucia Berra','Psiquiatria',1400,'Efectivo',1400,'08-jun','',False,'','',''),
      ('08-jun','Rodrigo Márquez','Andres Ramirez','Psicologia',550,'',NULL,'','',False,'','',''),
      ('08-jun','Diana Gómez','Stephanie Suel','Psiquiatria',1100,'Tarjera',1100,'08-jun','Synapsia',False,'','',''),
      ('08-jun','Jessica Vazquez','Marian Becerril','Psicologia',0,'',NULL,'','',False,'','',''),
      ('09-jun','Selene Garcia','Andrea Itzel Munguia Juarez','Psiquiatria',1400,'Tarjera',1400,'09-jun','Synapsia',True,'11-jun','2234',''),
      ('09-jun','Selene Garcia','Emiliano Muñoz','Psiquiatria',1100,'Efectivo',1100,'09-jun','',False,'','',''),
      ('09-jun','Selene Garcia','Esther Zarroca','Psiquiatria',0,'',NULL,'','',False,'','',''),
      ('09-jun','Selene Garcia','Paulina Elena Díaz','Psiquiatria',1100,'Tarjera',1100,'09-jun','Synapsia',False,'','',''),
      ('09-jun','Selene Garcia','Sofia Montserrat Ambia','Psiquiatria',1100,'Tarjera',1100,'09-jun','Synapsia',True,'23-jun','2262',''),
      ('09-jun','Selene Garcia','Yuriana Quiroz','Psiquiatria',500,'Transferencia',500,'09-jun','Médico',False,'','','envio compr.'),
      ('09-jun','Selene Garcia','Kayla Michelle Tarango','Psiquiatria',1100,'Tarjera',1100,'09-jun','Synapsia',False,'','',''),
      ('09-jun','Diana Gómez','Azul Zoe Morales','Psiquiatria',1100,'Tarjera',1100,'09-jun','Synapsia',False,'','',''),
      ('09-jun','Selene Garcia','Vivian Alonso','Psiquiatria',500,'',500,'09-jun','',False,'','',''),
      ('09-jun','Rodrigo Márquez','Cristopher Pineda','Psicologia',1100,'Tarjera',1100,'09-jun','Dr. Márquez',False,'','',''),
      ('09-jun','Selene Garcia','Santiago Román','Psiquiatria',600,'',600,'09-jun','',False,'','',''),
      ('09-jun','Diana Gómez','Maria del Socorro del Leon','Psiquiatria',1100,'Efectivo',1100,'09-jun','',False,'','',''),
      ('09-jun','Selene Garcia','Santiago Romero Ramirez','Psiquiatria',1400,'Tarjera',1400,'09-jun','Synapsia',False,'','',''),
      ('09-jun','Diana Gómez','Monica Nuño Gonzalez','Psiquiatria',1400,'Tarjera',1400,'09-jun','Synapsia',True,'11-jun','2235',''),
      ('09-jun','Diana Gómez','Danely Bernal','Psiquiatria',1400,'Efectivo',1400,'09-jun','',False,'','',''),
      ('09-jun','Selene Garcia','Cristopher Pineda','Psiquiatria',1100,'Tarjera',1100,'09-jun','Synapsia',False,'','',''),
      ('09-jun','Selene Garcia','Paola Jimena Salazar de Jesús','Psiquiatria',1400,'Tarjera',1400,'09-jun','Synapsia',True,'11-jun','2233',''),
      ('10-jun','Selene Garcia','Ximena Anahy Velázquez','Psiquiatria',1100,'Efectivo',1100,'10-jun','',False,'','',''),
      ('10-jun','Selene Garcia','María José Ceballos','Psiquiatria',1100,'Tarjera',1100,'10-jun','Synapsia',True,'11-jun','2231',''),
      ('10-jun','David Medina','Paola','Psicologia',800,'Efectivo',800,'10-jun','',False,'','',''),
      ('10-jun','Selene Garcia','Celeste Serrano','Psiquiatria',1100,'Efectivo',1100,'10-jun','',False,'','',''),
      ('10-jun','Selene Garcia','Adrian Hernández Cid','Psiquiatria',1100,'Transferencia',1100,'10-jun','Médico',False,'','','envio compr.'),
      ('10-jun','Jessica Vazquez','Christian Cienfuego','Psicologia',900,'Efectivo',900,'10-jun','',False,'','',''),
      ('10-jun','Jessica Vazquez','Axel Diaz','Evaluación Global',2000,'Efectivo',2000,'10-jun','',False,'','',''),
      ('10-jun','Selene Garcia','Mateo Ramirez Alvarez','Psiquiatria',1400,'Tarjera',1400,'10-jun','Synapsia',True,'faltan datos','',''),
      ('10-jun','Selene Garcia','Cruz Álvarez Rodríguez','Psiquiatria',1100,'Transferencia',1100,'10-jun','Synapsia',True,'11-jun','2232','envio compr.'),
      ('10-jun','Rodrigo Márquez','Alicia Garcia','Psicologia',0,'',NULL,'','',False,'','',''),
      ('10-jun','Jessica Vazquez','Ulrike','Psicologia',0,'',NULL,'','',False,'','',''),
      ('10-jun','Jessica Vazquez','María Hernández','Psicologia',0,'',NULL,'','',False,'','',''),
      ('10-jun','David Medina','Amir Soto','Psicologia',800,'Efectivo',800,'10-jun','',False,'','',''),
      ('10-jun','David Medina','Miguel Angel Davila','Psicologia',800,'Efectivo',800,'10-jun','',False,'','',''),
      ('10-jun','Diana Gómez','Gisela Espejel','Psiquiatria',1100,'Efectivo',1100,'10-jun','',False,'','',''),
      ('10-jun','Rodrigo Márquez','Jessica Giles','Psicologia',1100,'Transferencia',1100,'10-jun','Médico',False,'','','envio compr.'),
      ('10-jun','Diana Gómez','Aurelio Robles','Psiquiatria',1100,'Efectivo',1100,'10-jun','',False,'','',''),
      ('10-jun','Jessica Vazquez','Ana Maria Larios','Psicologia',0,'',NULL,'','',False,'','',''),
      ('10-jun','Jessica Vazquez','Norma Wendoline','Psicologia',900,'Efectivo',900,'10-jun','',False,'','',''),
      ('10-jun','David Medina','Dulce Gomez','Psicologia',800,'Efectivo',800,'10-jun','',False,'','',''),
      ('10-jun','Diana Gómez','Paulina Guadalupe Garcia','Psiquiatria',1100,'Tarjera',1100,'10-jun','Synapsia',False,'','',''),
      ('10-jun','Diana Gómez','Jose Roberto Ortiz','Psiquiatria',1100,'Efectivo',1100,'10-jun','',False,'','',''),
      ('10-jun','David Medina','Angeles Sughei','Psicologia',800,'',NULL,'','',False,'','',''),
      ('10-jun','Jessica Vazquez','Natalia Sepulveda','Psicologia',0,'',NULL,'','',False,'','',''),
      ('10-jun','David Medina','Alejandro Santin','Psicologia',800,'Transferencia',800,'11-jun','Médico',False,'','','envio compr.'),
      ('11-jun','David Medina','Siclair','Psicologia',800,'Efectivo',800,'11-jun','',False,'','',''),
      ('11-jun','David Medina','Antonio Dorantes','Psicologia',800,'Efectivo',800,'11-jun','',False,'','',''),
      ('11-jun','Rodrigo Márquez','Lupita','Psicologia',1100,'Tarjera',1100,'11-jun','Dr. Márquez',False,'','',''),
      ('11-jun','Diana Gómez','Raul Reyes Medina','Psiquiatria',1400,'Tarjera',1400,'11-jun','Synapsia',False,'','',''),
      ('11-jun','Rodrigo Márquez','Juan Carlos Becerril','Psicologia',1100,'Tarjera',1100,'11-jun','',False,'','',''),
      ('11-jun','Rodrigo Márquez','Nicole Pizarro','Psicologia',600,'Efectivo',600,'18-jun','',False,'','',''),
      ('11-jun','Jessica Vazquez','Daniela Rivera','Psicologia',1400,'Efectivo',1400,'11-jun','',False,'','',''),
      ('11-jun','Diana Gómez','Pedro Berminez','Psiquiatria',1100,'Efectivo',1100,'11-jun','',False,'','',''),
      ('11-jun','Rodrigo Márquez','Irving Avila','Psicologia',1800,'Tarjera',1800,'11-jun','Synapsia',True,'16-jun','2237',''),
      ('11-jun','Diana Gómez','Victor Hugo Fuentes','Psiquiatria',1100,'Tarjera',1100,'11-jun','Synapsia',False,'','',''),
      ('11-jun','Jessica Vazquez','Diego Emilio','Psicologia',900,'Efectivo',900,'11-jun','',False,'','',''),
      ('11-jun','Karina','Cecilia Gonzalez','Tanatología',934,'Transferencia',934,'11-jun','Synapsia',True,'16-jun','2236','envio compr.'),
      ('12-jun','Selene Garcia','Mateo Mendoza Dominguez','Psiquiatria',1100,'Efectivo',1100,'12-jun','',False,'','',''),
      ('12-jun','Selene Garcia','Ian Eduardo García','Psiquiatria',1100,'Transferencia',1100,'12-jun','Médico',False,'','','envio compr.'),
      ('12-jun','Selene Garcia','Moisés Pereira Rodríguez','Psiquiatria',1100,'Tarjera',1100,'12-jun','Synapsia',False,'','',''),
      ('12-jun','Jessica Vazquez','Axel Diaz','Evaluación Global',1000,'Efectivo',1000,'12-jun','',False,'','',''),
      ('12-jun','Selene Garcia','Berenice Saray Vara Carrillo','Psiquiatria',1100,'Efectivo',1100,'12-jun','',False,'','',''),
      ('12-jun','Jessica Vazquez','Nataly Camacho Márquez','Psicologia',1044,'Tarjera',1044,'12-jun','Jessi',False,'','',''),
      ('12-jun','Selene Garcia','Ricardo Valdivia','Psicologia',1100,'Tarjera',1100,'12-jun','Synapsia',False,'','',''),
      ('12-jun','Selene Garcia','Lua Marly','Psiquiatria',1100,'Efectivo',1100,'12-jun','',False,'','',''),
      ('12-jun','Jessica Vazquez','Michelle Peres','Psicologia',600,'Efectivo',600,'12-jun','',False,'','',''),
      ('12-jun','Rodrigo Márquez','Juan Diego Neri','Psicologia',1100,'Efectivo',1100,'12-jun','',False,'','',''),
      ('12-jun','Jessica Vazquez','Isabella Antillon','Evaluación Global',0,'',NULL,'','',False,'','',''),
      ('12-jun','Jessica Vazquez','Ivanna Miramontes','Psicologia',812,'Tarjera',812,'12-jun','Jessi',False,'','',''),
      ('12-jun','Jessica Vazquez','Axel Suarez','Psicologia',900,'',NULL,'','',False,'','',''),
      ('12-jun','Jessica Vazquez','Eduardo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('13-jun','Selene Garcia','Fryda González Chargoy','Psiquiatria',500,'',500,'13-jun','',False,'','',''),
      ('13-jun','Selene Garcia','Valeria montes','Psiquiatria',1100,'Tarjera',1100,'13-jun','Synapsia',True,'16-jun','2238',''),
      ('13-jun','Diana Gómez','Vicky Virto','Psiquiatria',600,'Efectivo',600,'13-jun','',False,'','',''),
      ('13-jun','Selene Garcia','Ana María González Martínez','Psiquiatria',1100,'Tarjera',1100,'13-jun','Synapsia',True,'16-jun','2239',''),
      ('13-jun','Diana Gómez','Diana Laura Saldivar','Psiquiatria',1100,'Efectivo',1100,'13-jun','',False,'','',''),
      ('13-jun','Diana Gómez','Alessandra Maciel','Psiquiatria',1100,'Efectivo',1100,'13-jun','',False,'','',''),
      ('13-jun','Selene Garcia','León Rodríguez','Psiquiatria',1100,'Tarjera',1100,'13-jun','Synapsia',False,'','',''),
      ('13-jun','Diana Gómez','Luis Enrique Hernández','Psiquiatria',1100,'Efectivo',1100,'13-jun','',False,'','',''),
      ('13-jun','Jessica Vazquez','Grecia','Psicologia',500,'Efectivo',500,'13-jun','',False,'','',''),
      ('13-jun','Rodrigo Márquez','Chris','Psiquiatria',0,'',NULL,'','',False,'','',''),
      ('13-jun','Jessica Vazquez','Dario Mercado','Psicologia',0,'',NULL,'','',False,'','',''),
      ('13-jun','Selene Garcia','Gilberto Salinas Chavez','Psiquiatria',1400,'Efectivo',1400,'13-jun','',False,'','',''),
      ('13-jun','Diana Gómez','Nubia Navez','Psiquiatria',1400,'Tarjera',1400,'13-jun','Synapsia',True,'23-jun','2264',''),
      ('13-jun','Rodrigo Márquez','Alejandro Alain De León','Psicologia',0,'',NULL,'','',False,'','',''),
      ('13-jun','Rodrigo Márquez','Azul Zoe Morales','Psicologia',550,'Efectivo',550,'13-jun','',False,'','',''),
      ('13-jun','Diana Gómez','Nancy Fajardo','Psiquiatria',1100,'Tarjera',1100,'13-jun','Synapsia',False,'','',''),
      ('13-jun','Selene Garcia','Fernanda Sánchez','Psiquiatria',1100,'Efectivo',1100,'13-jun','',False,'','',''),
      ('13-jun','Jessica Vazquez','Aisha','Psicologia',900,'Efectivo',900,'13-jun','',False,'','',''),
      ('13-jun','Rodrigo Márquez','Pablo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('13-jun','Diana Gómez','Valeria Monserrat Albarran','Psiquiatria',1100,'Tarjera',1100,'13-jun','Synapsia',False,'','','PAGO 200 EN EFECTIVO'),
      ('13-jun','Selene Garcia','Andrea Carolina Sánchez','Psiquiatria',700,'',700,'13-jun','',False,'','',''),
      ('13-jun','Selene Garcia','Matthew Ian','Psiquiatria',1100,'Tarjera',1100,'13-jun','Synapsia',True,'16-jun','2240',''),
      ('13-jun','Rodrigo Márquez','Daniela Peñaloza','Psicologia',1100,'Transferencia',1100,'13-jun','Médico',False,'','','envio compr.'),
      ('14-jun','Diana Gómez','Maria Teresa Miranda','Psiquiatria',1100,'Transferencia',1100,'14-jun','Synapsia',True,'16-jun','2241','envio compr.'),
      ('14-jun','Diana Gómez','Armando Navarro','Psiquiatria',1100,'Transferencia',1100,'15-jun','Synapsia',True,'16-jun','2242','envio compr.'),
      ('15-jun','Selene Garcia','Sherlin Fuentes Villalpando','Psiquiatria',1100,'Efectivo',1100,'15-jun','',False,'','',''),
      ('15-jun','Selene Garcia','Ximena Arisbeth Guadarrama','Psiquiatria',1100,'Efectivo',1100,'15-jun','',False,'','',''),
      ('15-jun','Selene Garcia','Eimy Valentina Sanchez','Psiquiatria',1400,'Transferencia',1400,'15-jun','Médico',False,'','','envio compr.'),
      ('15-jun','Selene Garcia','María Elena Maldonado','Psiquiatria',1100,'Efectivo',1100,'15-jun','',False,'','',''),
      ('15-jun','Selene Garcia','Ángel Efrén Alcantara','Psiquiatria',1100,'Efectivo',1100,'15-jun','',False,'','',''),
      ('15-jun','Selene Garcia','Diana Isabel Reyes','Psiquiatria',1400,'Tarjera',1400,'15-jun','Synapsia',False,'','',''),
      ('15-jun','Jessica Vazquez','Christian Cienfuego','Psicologia',900,'Efectivo',900,'15-jun','',False,'','',''),
      ('15-jun','Rodrigo Márquez','Aaron Garcia','Psicologia',1100,'Transferencia',1000,'15-jun','Médico',False,'','','envio compr.'),
      ('15-jun','Jessica Vazquez','Sofia Bonales','Psicologia',900,'Transferencia',900,'16-jun','Médico',False,'','','envio comp.'),
      ('15-jun','Rodrigo Márquez','Sofia Zamora','Psicologia',0,'',NULL,'','',False,'','',''),
      ('15-jun','Alejandra Tonanzin','???','Psicologia',0,'',NULL,'','',False,'','',''),
      ('15-jun','Alejandra Tonanzin','Mauricio','Psicologia',0,'',NULL,'','',False,'','',''),
      ('15-jun','Rodrigo Márquez','Juan Cañas','Psicologia',1100,'Tarjera',1100,'15-jun','Synapsia',True,'faltan datos','',''),
      ('15-jun','Diana Gómez','Nayeli Davila Miranda','Psiquiatria',1100,'Efectivo',1100,'15-jun','',False,'','',''),
      ('15-jun','Jessica Vazquez','Mia Nataly','Psicologia',900,'Efectivo',900,'15-jun','',False,'','',''),
      ('15-jun','Rodrigo Márquez','Obed Gonzalez','Psicologia',1100,'Tarjera',1100,'15-jun','Synapsia',True,'16-jun','2243',''),
      ('15-jun','Jessica Vazquez','Sofia Alanis','Psicologia',900,'Efectivo',900,'15-jun','',False,'','',''),
      ('15-jun','Diana Gómez','Norma Wendoline','Psiquiatria',550,'Transferencia',550,'15-jun','Médico',False,'','','envio compr.'),
      ('15-jun','Diana Gómez','Dayana Yamileth Calzada','Psiquiatria',1100,'Efectivo',1100,'15-jun','',False,'','',''),
      ('15-jun','Rodrigo Márquez','Cariño','Psicologia',1100,'Tarjera',1100,'15-jun','Synapsia',True,'faltan datos','',''),
      ('15-jun','Jessica Vazquez','Marian Becerril','Psicologia',0,'',NULL,'','',False,'','',''),
      ('15-jun','Diana Gómez','Jacobo Cuellas','Psiquiatria',700,'Efectivo',700,'15-jun','',False,'','',''),
      ('15-jun','David Medina','Miguel Angel Davila','Psicologia',800,'Efectivo',800,'15-jun','',False,'','',''),
      ('16-jun','David Medina','Corina','Psicologia',800,'',800,'16-jun','',False,'','',''),
      ('16-jun','Selene Garcia','Viridiana Valdez','Psiquiatria',1100,'Transferencia',1100,'16-jun','Synapsia',True,'16-jun','2244','envio compr.'),
      ('16-jun','Selene Garcia','Diego Zahir Sánchez López','Psiquiatria',1100,'Tarjera',1100,'16-jun','Synapsia',True,'16-jun','2245',''),
      ('16-jun','Selene Garcia','Ataly Vázquez Contreras','Psiquiatria',1100,'Transferencia',1100,'16-jun','Synapsia',True,'16-jun','2247','envio compr.'),
      ('16-jun','Selene Garcia','Bruno Mathias García Ramos','Psiquiatria',1400,'Tarjera',1400,'16-jun','Synapsia',True,'16-jun','2246',''),
      ('16-jun','Selene Garcia','Mariam valladares','Psiquiatria',1100,'Efectivo',1100,'16-jun','',False,'','',''),
      ('16-jun','Selene Garcia','Issac Arturo García Martinez','Psiquiatria',0,'',NULL,'','',False,'','',''),
      ('16-jun','David Medina','???','Psicologia',800,'',800,'16-jun','',False,'','',''),
      ('16-jun','Diana Gómez','Raul Herrera','Psiquiatria',1400,'Tarjera',1400,'16-jun','Synapsia',True,'faltan datos','',''),
      ('16-jun','Diana Gómez','Aimee Cardenas','Psiquiatria',1100,'Tarjera',1100,'16-jun','Synapsia',True,'19-jun','2249',''),
      ('16-jun','Selene Garcia','Alberto Hernández González','Psiquiatria',1100,'Efectivo',1100,'16-jun','',False,'','',''),
      ('16-jun','Selene Garcia','Edgar Ramón','Psiquiatria',1100,'Efectivo',1100,'16-jun','',False,'','',''),
      ('16-jun','Rodrigo Márquez','Román Cordova','Psiquiatria',1100,'Tarjera',1100,'16-jun','Synapsia',False,'','',''),
      ('16-jun','Diana Gómez','Erendida Mendoza','Psiquiatria',1100,'Tarjera',1100,'16-jun','Synapsia',True,'19-jun','2250',''),
      ('16-jun','Diana Gómez','Araceli Fuentes','Psiquiatria',1100,'Efectivo',1100,'16-jun','',False,'','',''),
      ('17-jun','Selene Garcia','Alan Israel Perez Molina','Psiquiatria',1400,'Efectivo',1400,'17-jun','',False,'','',''),
      ('17-jun','David Medina','Paola','Psicologia',800,'',800,'17-jun','',False,'','',''),
      ('17-jun','Selene Garcia','José Luis Velazquez Arias','Psiquiatria',1100,'Efectivo',1100,'17-jun','',False,'','',''),
      ('17-jun','Selene Garcia','Diana Abigail Vilchis','Psiquiatria',1100,'Efectivo',1100,'17-jun','',False,'','',''),
      ('17-jun','Jessica Vazquez','Christian Cienfuego','Psicologia',900,'',NULL,'','',False,'','',''),
      ('17-jun','Selene Garcia','Elvira Alicia Martínez','Psiquiatria',700,'',700,'17-jun','',False,'','',''),
      ('17-jun','Rodrigo Márquez','Margarita Morales','Psicologia',1100,'Efectivo',1100,'17-jun','',False,'','',''),
      ('17-jun','Selene Garcia','Lizbeth Sugeili Trujillo Piedra','Psiquiatria',500,'Transferencia',500,'17-jun','Médico',False,'','','envio compr.'),
      ('17-jun','Rodrigo Márquez','Gisela Espejel','Psicologia',1100,'Efectivo',1100,'17-jun','',False,'','',''),
      ('17-jun','Jessica Vazquez','Axel Diaz','Evaluación Global',750,'Efectivo',750,'17-jun','',False,'','',''),
      ('17-jun','David Medina','Amir Soto','Psicologia',800,'',800,'17-jun','',False,'','',''),
      ('17-jun','David Medina','Daniela','Psicologia',800,'',800,'','',False,'','',''),
      ('17-jun','Alejandra Tonanzin','Bernardo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('17-jun','Jessica Vazquez','Maricela','Psicologia',800,'Efectivo',800,'17-jun','',False,'','',''),
      ('17-jun','David Medina','Dulce Gomez','Psicologia',800,'Efectivo',800,'17-jun','',False,'','',''),
      ('17-jun','Diana Gómez','Bernardo Nieto','Psiquiatria',1100,'Efectivo',1100,'17-jun','',False,'','',''),
      ('17-jun','David Medina','Sughey','Psicologia',800,'',NULL,'','',False,'','',''),
      ('17-jun','Diana Gómez','Margarita Enriquez','Psiquiatria',1100,'Efectivo',1100,'17-jun','',False,'','',''),
      ('17-jun','Octavio Márquez','Luis Brunett','Psiquiatria',1160,'Tarjera',1160,'17-jun','Synapsia',True,'19-jun','2251',''),
      ('17-jun','Rodrigo Márquez','Andrea Melissa','Psicologia',1100,'Tarjera',1100,'17-jun','Dr. Márquez',False,'','',''),
      ('17-jun','Jessica Vazquez','Norma Wendoline','Psicologia',900,'Transferencia',900,'16-jun','Médico',False,'','','envio compr.'),
      ('17-jun','Diana Gómez','Ariadna Orozco','Psiquiatria',0,'',NULL,'','',False,'','',''),
      ('17-jun','David Medina','Alejandro Santin','Psicologia',800,'Transferencia',800,'17-jun','Médico',False,'','','envio compr.'),
      ('17-jun','Diana Gómez','Karol Camila Flores','Psiquiatria',1100,'Transferencia',1100,'17-jun','Synapsia',True,'19-jun','2252','envio compr.'),
      ('17-jun','Jessica Vazquez','Fam Duran','Psicologia',1800,'',NULL,'','',False,'','',''),
      ('18-jun','Selene Garcia','Joshua Harim Atenogenes','Psiquiatria',1400,'Efectivo',1400,'18-jun','',False,'','',''),
      ('18-jun','David Medina','Juan Antonio Dorante','Psicologia',800,'Efectivo',800,'18-jun','',False,'','',''),
      ('18-jun','Selene Garcia','Karla Estrada Olvera','Psiquiatria',1100,'Tarjera',1100,'18-jun','Synapsia',True,'19-jun','2253',''),
      ('18-jun','Karla','Paola','Nutrición',0,'',NULL,'','',False,'','',''),
      ('18-jun','Selene Garcia','Jordi Flores','Psiquiatria',1100,'Efectivo',1100,'18-jun','',False,'','',''),
      ('18-jun','Selene Garcia','Cynthia García','Psiquiatria',1100,'Transferencia',1100,'18-jun','Médico',False,'','','envio compr.'),
      ('18-jun','Rodrigo Márquez','Victoria Martínez Martínez','Psicologia',1100,'Tarjera',1100,'18-jun','Synapsia',True,'faltan datos','',''),
      ('18-jun','Jessica Vazquez','Mayte Reyes López','Psicologia',900,'Efectivo',900,'18-jun','',False,'','',''),
      ('18-jun','Diana Gómez','Erick Yakin Lopez','Psiquiatria',1100,'Tarjera',1100,'18-jun','Synapsia',True,'19-jun','2254',''),
      ('18-jun','Diana Gómez','Danitza Mendoza','Psiquiatria',1100,'Efectivo',1100,'18-jun','',False,'','',''),
      ('18-jun','Rodrigo Márquez','Pilar Garcíagalán','Psicologia',750,'Transferencia',750,'18-jun','Médico',False,'','','envio compr.'),
      ('18-jun','Rodrigo Márquez','Nicole Pizarro','Psicologia',600,'Efectivo',600,'18-jun','',False,'','',''),
      ('18-jun','Diana Gómez','Maria Jose  Reyes','Psiquiatria',1100,'Tarjera',1100,'18-jun','Synapsia',False,'','',''),
      ('18-jun','Jessica Vazquez','Rene Santin','Psicologia',0,'',NULL,'','',False,'','',''),
      ('18-jun','Diana Gómez','Marco Vinicio Paniagua','Psiquiatria',1100,'Tarjera',1100,'18-jun','Synapsia',True,'19-jun','2255',''),
      ('18-jun','Jessica Vazquez','Diego Emilio','Psicologia',900,'',NULL,'','',False,'','',''),
      ('19-jun','Selene Garcia','Mabel Uribe Yamin','Psiquiatria',1400,'Tarjera',1400,'19-jun','Synapsia',False,'','',''),
      ('19-jun','Selene Garcia','Katia Jordan','Psiquiatria',1100,'Efectivo',1100,'19-jun','',False,'','',''),
      ('19-jun','Selene Garcia','Ximena Ramírez Valle','Psiquiatria',500,'',500,'19-jun','',False,'','',''),
      ('19-jun','Selene Garcia','Jovana Báez Chávez','Psiquiatria',1100,'Transferencia',1100,'19-jun','Synapsia',True,'19-jun','2256','envio compr.'),
      ('19-jun','Rodrigo Márquez','Edwin','Psicologia',1800,'Efectivo',1800,'19-jun','',False,'','',''),
      ('19-jun','Selene Garcia','Victor Acevedo','Psiquiatria',1400,'Tarjera',1400,'19-jun','Synapsia',True,'faltan datos','',''),
      ('19-jun','Selene Garcia','Maximiliano Becerril','Psiquiatria',1100,'Efectivo',1100,'19-jun','',False,'','',''),
      ('19-jun','Jessica Vazquez','Isabella Antillon','Evaluación Global',2500,'Efectivo',2500,'19-jun','',False,'','',''),
      ('19-jun','Rodrigo Márquez','Azul Zoe Morales','Psicologia',550,'Tarjera',550,'19-jun','Dr. Márquez',False,'','',''),
      ('19-jun','Rodrigo Márquez','Jose Gonzalez','Psicologia',1100,'Efectivo',1100,'19-jun','',False,'','','debe $100'),
      ('19-jun','Octavio Márquez','Alejandro Odabachea','Psiquiatria',1160,'Transferencia',1160,'22-jun','Synapsia',True,'23-jun','2265','envio compr.'),
      ('19-jun','Jessica Vazquez','Axel Suarez','Psicologia',750,'Efectivo',750,'19-jun','',False,'','',''),
      ('19-jun','Rodrigo Márquez','Carla Martinez','Psicologia',0,'',NULL,'','',False,'','',''),
      ('19-jun','Rodrigo Márquez','Juan Carlos Becerril','Psicologia',1100,'Tarjera',1100,'19-jun','Dr. Márquez',False,'','',''),
      ('20-jun','Selene Garcia','Abigail Balbuena','Psiquiatria',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('20-jun','Diana Gómez','Oscar Lopez Lopez','Psiquiatria',1100,'Tarjera',1100,'20-jun','Synapsia',True,'23-jun','2257',''),
      ('20-jun','Selene Garcia','Renata Aimee','Psiquiatria',1100,'Tarjera',1100,'20-jun','Synapsia',False,'','',''),
      ('20-jun','Diana Gómez','Victoria Martínez Martínez','Psiquiatria',1400,'Efectivo',1400,'20-jun','',False,'','',''),
      ('20-jun','Jessica Vazquez','Eduardo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('20-jun','Selene Garcia','Fausto Perez','Psiquiatria',500,'',500,'20-may','',False,'','',''),
      ('20-jun','Diana Gómez','Camarina Caballero','Psiquiatria',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('20-jun','Diana Gómez','Veronica Alvarez','Psiquiatria',1400,'Transferencia',1400,'20-jun','Synapsia',True,'23-jun','2259','envio compr.'),
      ('20-jun','Selene Garcia','Matteo Ruiz Díaz','Psiquiatria',1100,'Tarjera',1100,'20-jun','Synapsia',True,'23-jun','2258',''),
      ('20-jun','Selene Garcia','Carlos Guillermo Valle','Psiquiatria',1100,'Tarjera',1100,'20-jun','Synapsia',True,'','',''),
      ('20-jun','Jessica Vazquez','Dario Mercado','Psicologia',0,'',NULL,'','',False,'','',''),
      ('20-jun','Rodrigo Márquez','Ivette Garcia','Psicologia',700,'Efectivo',700,'20-jun','',False,'','',''),
      ('20-jun','Rodrigo Márquez','Jose Manuel Ruiz','Psicologia',1100,'Tarjera',1100,'20-jun','Synapsia',True,'23-mar','2260',''),
      ('20-jun','Diana Gómez','Zulema Gonzalez','Psiquiatria',1100,'Tarjera',1100,'20-jun','Synapsia',False,'','',''),
      ('20-jun','Selene Garcia','José Iker Macías Medrano','Psiquiatria',1400,'Tarjera',1400,'20-jun','Synapsia',True,'23-jun','2261',''),
      ('20-jun','Jessica Vazquez','Aisha','Psicologia',900,'Efectivo',900,'20-jun','',False,'','',''),
      ('20-jun','Diana Gómez','Emma Wendoline Mondragón','Psiquiatria',1100,'Tarjera',1100,'20-jun','Synapsia',False,'','',''),
      ('20-jun','Selene Garcia','Ayelen Torres Romero','Psiquiatria',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('20-jun','Jessica Vazquez','Barbara','Psicologia',800,'Efectivo',800,'20-jun','',False,'','',''),
      ('20-jun','Rodrigo Márquez','Carlos Eduardo','Psicologia',1100,'Tarjera',1100,'20-jun','Dr. Márquez',False,'','',''),
      ('20-jun','Diana Gómez','Carlos Emmanuel de Jesús','Psiquiatria',1400,'Efectivo',1400,'20-jun','',False,'','',''),
      ('20-jun','Selene Garcia','Aidee Morán','Psiquiatria',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('22-jun','Selene Garcia','Jose Alfonso Albarran','Psiquiatria',1100,'Transferencia',1100,'20-jun','Médico',False,'','','envio compr.'),
      ('22-jun','Alejandra Tonanzin','???','Psicologia',0,'',NULL,'','',False,'','',''),
      ('22-jun','Selene Garcia','Paola Cienfuegos','Psiquiatria',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('22-jun','Selene Garcia','José Antonio Mejía Ventolero','Psiquiatria',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('22-jun','Selene Garcia','Leticia Colin','Psiquiatria',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('22-jun','Rodrigo Márquez','Zerafino Cardoso','Psicologia',0,'',NULL,'','',False,'','',''),
      ('22-jun','Selene Garcia','Azul Souling González Rico','Psiquiatria',1400,'Efectivo',NULL,'','',False,'','',''),
      ('22-jun','Selene Garcia','Daniela Gutiérrez','Psiquiatria',1100,'Tarjera',1100,'20-jun','Synapsia',False,'','',''),
      ('22-jun','Rodrigo Márquez','Patricia Ruiz','Psicologia',1100,'Efectivo',1100,'20-jun','',False,'','',''),
      ('22-jun','Jessica Vazquez','Christian Cienfuego','Psicologia',900,'',NULL,'','',False,'','',''),
      ('22-jun','Jessica Vazquez','Paulo','Psicologia',0,'',NULL,'','',False,'','',''),
      ('22-jun','Rodrigo Márquez','Obed Gonzalez','Psicologia',1100,'Tarjera',1100,'22-jun','Synapsia',True,'23-jun','2263',''),
      ('22-jun','Diana Gómez','Carolla Samano','Psiquiatria',1100,'Tarjera',1100,'22-jun','Synapsia',False,'','',''),
      ('22-jun','Rodrigo Márquez','Aaron Garcia','Psicologia',1000,'Transferencia',1000,'22-jun','Médico',False,'','','envio compr.'),
      ('22-jun','Octavio Márquez','Sigfrid Leonardo','Psiquiatria',500,'Efectivo',500,'22-jun','',False,'','',''),
      ('22-jun','Rodrigo Márquez','Carolla Samano','Psicologia',1100,'Efectivo',1100,'22-jun','',False,'','',''),
      ('22-jun','Diana Gómez','Daniel Lara','Psiquiatria',1100,'Transferencia',1100,'22-jun','Médico',False,'','','envio compr.'),
      ('22-jun','Rodrigo Márquez','Cariño','Psicologia',1100,'Efectivo',1100,'22-jun','',False,'','',''),
      ('22-jun','Jessica Vazquez','Sofia Alanis','Psicologia',1044,'Tarjera',1044,'22-jun','Jessi',False,'','',''),
      ('22-jun','Diana Gómez','Carolina Guzman','Psiquiatria',1100,'Efectivo',1100,'22-jun','',False,'','',''),
      ('22-jun','Jessica Vazquez','Marian Becerril','Psicologia',0,'',NULL,'','',False,'','',''),
      ('22-jun','David Medina','Miguel Angel Davila','Psicologia',800,'Efectivo',800,'22-jun','',False,'','',''),
      ('23-jun','Selene Garcia','José Vicente Ibarra Ayala','Psiquiatria',1100,'Tarjera',1100,'23-jun','Synapsia',True,'23-jun','2266',''),
      ('23-jun','Selene Garcia','Frida Rojas Cortés Gallardo','Psiquiatria',1100,'Efectivo',1100,'23-jun','',False,'','',''),
      ('23-jun','Selene Garcia','Alondra Álvarez','Psiquiatria',1100,'Transferencia',1100,'23-jun','Médico',False,'','','envio compr.'),
      ('23-jun','Selene Garcia','Cristopher Juvenal Arizmendi','Psiquiatria',1400,'Tarjera',1100,'23-jun','Synapsia',False,'','',''),
      ('23-jun','Rodrigo Márquez','Victoria Martínez Martínez','Psicologia',1100,'Efectivo',1100,'23-jun','',False,'','',''),
      ('23-jun','Diana Gómez','Daniela Hinojosa','Psiquiatria',1100,'Tarjera',1100,'23-jun','Synapsia',False,'','',''),
      ('23-jun','Selene Garcia','Karina Bustamante','Psiquiatria',1100,'Efectivo',1100,'23-mar','Synapsia',True,'','','pendiente'),
      ('23-jun','Diana Gómez','Luis Guillermo Flores','Psiquiatria',1100,'Tarjera',1100,'23-jun','Synapsia',True,'','',''),
      ('23-jun','Selene Garcia','Ana Carmen Villagrán','Psiquiatria',1100,'Efectivo',1100,'23-jun','',False,'','',''),
      ('23-jun','Rodrigo Márquez','Geovanna','Psicologia',1100,'Efectivo',1100,'23-jun','',False,'','',''),
      ('23-jun','Selene Garcia','Monserrat Macias Gonzalez','Psiquiatria',1400,'Tarjera',1400,'23-jun','Synapsia',False,'','',''),
      ('23-jun','Diana Gómez','Elena Guadalupe Plata','Psiquiatria',1100,'Efectivo',1100,'23-jun','',False,'','',''),
      ('23-jun','Rodrigo Márquez','Karla Gabriela Alcantara','Psicologia',1100,'Tarjera',1100,'23-jun','Synapsia',True,'faltan datos','',''),
      ('23-jun','Selene Garcia','Axel Suarez','Psiquiatria',600,'Efectivo',600,'23-jun','',False,'','',''),
      ('23-jun','Diana Gómez','Raul Plata Gonzalez','Psiquiatria',1100,'Efectivo',1100,'23-jun','',False,'','',''),
      ('23-jun','Rodrigo Márquez','Emmanuel Terron','Psicologia',1100,'',NULL,'','',False,'','',''),
      ('23-jun','Selene Garcia','Joana Toribio','Psiquiatria',0,'',NULL,'','',False,'','',''),
      ('23-jun','Diana Gómez','Alexis Gonzalez','Psiquiatria',1400,'Tarjera',1400,'23-jun','Synapsia',True,'faltan datos','',''),
      ('24-jun','David Medina','Paola','Psicologia',800,'Efectivo',800,'24-jun','',False,'','',''),
      ('24-jun','Selene Garcia','Sofia Bonales','Psiquiatria',0,'',NULL,'','',False,'','',''),
      ('24-jun','David Medina','Corina','Psicologia',800,'Efectivo',800,'24-jun','',False,'','',''),
      ('24-jun','Selene Garcia','Diego Gamez','Psiquiatria',1100,'Efectivo',1100,'24-jun','',False,'','','$500 tranfirió a médico'),
      ('24-jun','Jessica Vazquez','Christian Cienfuego','Psicologia',900,'Efectivo',900,'24-jun','',False,'','',''),
      ('24-jun','Rodrigo Márquez','Hilda Mendez','Psicologia',1100,'',NULL,'','',False,'','',''),
      ('24-jun','Selene Garcia','Jesse Renato Lazaro','Psiquiatria',1100,'Efectivo',1100,'24-jun','',False,'','',''),
      ('24-jun','Selene Garcia','Diego Javier Herrera Gonzalez','Psiquiatria',1400,'Efectivo',1400,'24-jun','',False,'','',''),
      ('24-jun','Rodrigo Márquez','Guadalupe Yamin','Psicologia',1100,'Tarjera',1100,'24-jun','Dr. Márquez',False,'','',''),
      ('24-jun','Jessica Vazquez','Ulrike','Psicologia',0,'',NULL,'','',False,'','',''),
      ('24-jun','Rodrigo Márquez','Gisela Espejel','Psicologia',1100,'Efectivo',1100,'24-jun','',False,'','',''),
      ('24-jun','Selene Garcia','Andres Jasiel Macedo Alanis','Psiquiatria',1400,'Efectivo',1400,'24-jun','',False,'','',''),
      ('24-jun','Rodrigo Márquez','Gabriela Villicaña','Psicologia',1100,'Efectivo',1100,'24-jun','',False,'','',''),
      ('24-jun','Jessica Vazquez','Francia Muñoz','Psicologia',0,'',NULL,'','',False,'','',''),
      ('24-jun','David Medina','Amir Soto','Psicologia',800,'',NULL,'','',False,'','',''),
      ('24-jun','Rodrigo Márquez','Andres Ramirez','Psicologia',550,'Tarjera',550,'24-jun','',False,'','',''),
      ('24-jun','Jessica Vazquez','Ana Maria Larios','Psicologia',0,'',NULL,'','',False,'','',''),
      ('24-jun','Diana Gómez','Shantina Mary','Psiquiatria',1100,'Efectivo',1100,'24-jun','Synapsia',True,'','',''),
      ('24-jun','Rodrigo Márquez','Jose Antonio Ortiz','Psicologia',0,'',NULL,'','',False,'','',''),
      ('24-jun','Rodrigo Márquez','Carla Martinez','Psicologia',1100,'Efectivo',1100,'24-jun','',False,'','',''),
      ('24-jun','Jessica Vazquez','Norma Wendoline','Psicologia',900,'Transferencia',900,'24-jun','Médico',False,'','','envio compr.'),
      ('24-jun','Diana Gómez','Lucero sánchez','Psiquiatria',1100,'Efectivo',1100,'24-jun','',False,'','',''),
      ('24-jun','David Medina','Angeles Sughei','Psicologia',800,'Efectivo',800,'24-jun','',False,'','',''),
      ('24-jun','Diana Gómez','Moises Elias Montes','Psiquiatria',1100,'Efectivo',1100,'24-jun','',False,'','',''),
      ('24-jun','Jessica Vazquez','Mayte Reyes López','Evaluación Global',3000,'Efectivo',3000,'24-jun','',False,'','',''),
      ('24-jun','David Medina','Alejandro Santin','Psicologia',800,'Transferencia',800,'25-jun','Médico',False,'','','envio compr.'),
      ('25-jun','Selene Garcia','Ximena Venegas Chavez','Psiquiatria',1100,'Tarjera',1100,'25-jun','Synapsia',False,'','',''),
      ('25-jun','Selene Garcia','Miledy Ayón Israde','Psiquiatria',1100,'Tarjera',1100,'25-jun','Synapsia',True,'','',''),
      ('25-jun','Selene Garcia','Iztli Vanessa','Psiquiatria',1100,'Transferencia',1100,'25-jun','Médico',False,'','','envio compr.'),
      ('25-jun','Selene Garcia','Santiago Sotelo','Psiquiatria',0,'',NULL,'','',False,'','','')
    ) AS t(fecha,medico,paciente,servicio,costo,forma,cobrado,fecha_pago,transfer,has_invoice,fecha_fact,folio,coments)
  )
  INSERT INTO public.consultation_log (health_unit_id, record_date, specialist_name, patient_name, service_type, cost, payment_method, amount_collected, payment_date, transfer_to, has_invoice, invoice_date, invoice_folio, notes, created_by)
  SELECT
    synapsia_id,
    TO_DATE(CONCAT(t.fecha, '-2026'), 'DD-Mon-YYYY'),
    t.medico,
    t.paciente,
    t.servicio,
    t.costo,
    NULLIF(t.forma, ''),
    t.cobrado,
    CASE WHEN t.fecha_pago = '' THEN NULL ELSE TO_DATE(CONCAT(t.fecha_pago, '-2026'), 'DD-Mon-YYYY') END,
    NULLIF(t.transfer, ''),
    t.has_invoice,
    CASE WHEN t.fecha_fact IN ('', 'faltan datos') THEN NULL ELSE TO_DATE(CONCAT(t.fecha_fact, '-2026'), 'DD-Mon-YYYY') END,
    NULLIF(t.folio, ''),
    NULLIF(t.coments, ''),
    admin_user_id
  FROM data t;
END;
$$;

-- Update updated_at to created_at for all rows
UPDATE public.consultation_log SET updated_at = created_at WHERE updated_at = created_at;

